API_ID = 34446649  # api id
API_HASH = "8dc570c08d8e35e88fb9bfc73c65d7fa"  # api hash

BOT_TOKEN = "8735534617:AAFNBedzWsDRcsiw6GXBq7QAHbqJSJiDw0w"  # bot token


## REDIS
HOST = "redis-15392.c304.europe-west1-2.gce.cloud.redislabs.com"  # redis host uri
PORT = "15392"  # redis port
PASSWORD = "cbw7xHuW3uJmddWJRRqxiSWmRvKi81GM"  # redis password

PRIVATE_CHAT_ID = -1003951808679  # CHAT WHERE YOU WANT TO STORE VIDEOS
COOKIE = "# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
.1024terabox.com	TRUE	/	TRUE	1784382845	_rdt_em	:0c32bebfcbd4816e23c70c97603796ef391a3e88f783cab16e8b116ffa599bf5,3a3517aec9c964cb5f68fadcc6ca97908c990348487c4bbd484b70e7f4dafd69,6022ff9424d023ad1b5546c27c687bc02ad92f77fc51cc2bd057c298a4915c4b
.1024terabox.com	TRUE	/	FALSE	1779198869	lang	en
.dm.1024terabox.com	TRUE	/	FALSE	1808142825	_pin_unauth	dWlkPU16Qm1aREJpTjJJdE9UUXpPQzAwTTJObUxXRm1NVE10TkRCaFkyTTVNV001TVRZMg
.1024terabox.com	TRUE	/	FALSE	1811166868	_ga_06ZNKL8C2E	GS2.1.s1776606848$o3$g1$t1776606868$j40$l0$h0
.1024terabox.com	TRUE	/	FALSE	1804469970	_pin_unauth	dWlkPU16Qm1aREJpTjJJdE9UUXpPQzAwTTJObUxXRm1NVE10TkRCaFkyTTVNV001TVRZMg
dm.1024terabox.com	FALSE	/	FALSE	1779198855	ndut_fmv	f64f2274f08ebf63e8aa89cbb1657556f486c51a023cf8b7b1f4966de8a2b25a1be9f742bc709d20391f2eae961230b625610e1cb26fe4e2a31a4bd2fced3d511be4523d6afd9714efd8a16f965e762ef358c2f83f3199c92b2d4db27d2"  # COOKIE FOR AUTHENTICATION (get from chrome dev tools) ex: "PANWEB=1; csrfToken=; lang=en; TSID=; __bid_n=; _ga=; __stripe_mid=; ndus=; browserid==; ndut_fmt=; _ga_06ZNKL8C2E=" (dont use this)
ADMINS = [7892805795]
